/** Centralized path constants — change paths in one place. */
export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  me: '/me',
  changePassword: '/me/change-password',
  exportMe: '/me/export',
  forms: '/forms',
  form: (id: string) => `/forms/${id}`,
  publish: (id: string) => `/forms/${id}/publish`,
  close: (id: string) => `/forms/${id}/close`,
  duplicate: (id: string) => `/forms/${id}/duplicate`,
  formResponses: (id: string) => `/forms/${id}/responses`,
  formExport: (id: string) => `/forms/${id}/export.csv`,
  formAnalytics: (id: string) => `/forms/${id}/analytics`,
  response: (id: string) => `/responses/${id}`,
  responseSpam: (id: string) => `/responses/${id}/spam`,
  apiKeys: '/api-keys',
  apiKey: (id: string) => `/api-keys/${id}`,
  revealApiKey: (id: string) => `/api-keys/${id}/reveal`,
  formWebhooks: (id: string) => `/forms/${id}/webhooks`,
  webhook: (id: string) => `/webhooks/${id}`,
  testWebhook: (id: string) => `/webhooks/${id}/test`,
  webhookDeliveries: (id: string) => `/webhooks/${id}/deliveries`,
  retryDelivery: (id: string, dId: string) => `/webhooks/${id}/deliveries/${dId}/retry`,
  publicForm: (slug: string) => `/public/forms/${slug}`,
  publicStart: (formId: string) => `/public/forms/${formId}/start`,
  publicSubmit: (formId: string) => `/public/forms/${formId}/submit`,
  teams: '/teams',
  teamMembers: (id: string) => `/teams/${id}/members`,
  invite: (id: string) => `/teams/${id}/invite`,
  acceptTeam: '/teams/accept',
  removeMember: (id: string, userId: string) => `/teams/${id}/members/${userId}`,
  checkout: '/billing/checkout',
  portal: '/billing/portal',
} as const;
